# This is a basic workflow to help you get started with Actions

name: deploy-payments

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
    paths:
      - 'payments/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: cd payments && docker build -t usmanzaheer/ticketing-payments .
      
      - name: Login to dockerhub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push payments image to dockerhub
        run: docker push usmanzaheer/ticketing-payments
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Switch kubectl context to digital ocean
        run: doctl kubernetes cluster kubeconfig save ticketing
      
      - run: kubectl rollout restart deployment payments-depl
        name: Restart kubectl deployment